# Generated by Django 5.0.14 on 2026-07-21 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title or name of the document', max_length=255)),
                ('uploaded_file', models.FileField(help_text='The path to the uploaded document file', upload_to='contracts/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('SLA', 'Service Level Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('VENDOR', 'Vendor Agreement'), ('PARTNERSHIP', 'Partnership Agreement'), ('OTHER', 'Other Legal Document')], default='OTHER', help_text='Type of legal contract/document', max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', help_text='Processing status of the document', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
                ('extracted_text', models.TextField(blank=True, help_text='Full text content extracted from the document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this database record was last updated')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='The user who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'contracts_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
