# Generated by Django 5.0.14 on 2026-07-21 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the extracted clause', primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('termination', 'Termination'), ('indemnification', 'Indemnification'), ('limitation_of_liability', 'Limitation of Liability'), ('governing_law', 'Governing Law'), ('intellectual_property', 'Intellectual Property'), ('force_majeure', 'Force Majeure'), ('other', 'Other')], default='other', help_text='The classification/type of the clause', max_length=100)),
                ('clause_text', models.TextField(help_text='The raw text of the extracted clause')),
                ('page_number', models.IntegerField(blank=True, help_text='The page number where the clause was found in the document', null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score of the extraction (between 0.0000 and 1.0000)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this clause was extracted and saved')),
                ('document', models.ForeignKey(help_text='The document from which this clause was extracted', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_clauses', to='contracts.document')),
            ],
            options={
                'verbose_name': 'Extracted Clause',
                'verbose_name_plural': 'Extracted Clauses',
                'db_table': 'parser_extracted_clause',
                'ordering': ['page_number', 'created_at'],
            },
        ),
    ]
