# Generated by Django 6.0.7 on 2026-07-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('CONFIDENTIALITY', 'Confidentiality'), ('LIABILITY', 'Limitation of Liability'), ('INDEMNIFICATION', 'Indemnification'), ('TERMINATION', 'Termination'), ('FORCE_MAJEURE', 'Force Majeure'), ('ARBITRATION', 'Arbitration & Dispute Resolution'), ('INTELLECTUAL_PROPERTY', 'Intellectual Property'), ('GENERAL', 'General Provisions')], db_index=True, default='GENERAL', max_length=50)),
                ('text', models.TextField()),
                ('page_number', models.IntegerField(default=1)),
                ('start_pos', models.IntegerField(default=0)),
                ('end_pos', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
            ],
            options={
                'ordering': ['page_number', 'start_pos'],
            },
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.IntegerField(default=0, help_text='Score from 0 (Safe) to 100 (Extremely Risky)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_index=True, default='LOW', max_length=20)),
                ('risk_summary', models.TextField(blank=True, null=True)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analysis', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='RiskClauseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Severity')], default='MEDIUM', max_length=20)),
                ('explanation', models.TextField()),
                ('highlighted_text', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_flags', to='analysis.clause')),
                ('risk_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='analysis.riskanalysis')),
            ],
        ),
    ]
