# Generated by Django 6.0.7 on 2026-07-27 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='contracts/%Y/%m/')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('ANALYZED', 'Analyzed'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.JSONField(default=list, help_text='Extracted list of companies or organizations.')),
                ('dates', models.JSONField(default=list, help_text='Key dates identified in contract text.')),
                ('effective_date', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('governing_law', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_parties', models.JSONField(default=list, help_text='Primary identified contract parties.')),
                ('total_clauses_extracted', models.IntegerField(default=0)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='documents.document')),
            ],
        ),
    ]
