# Generated by Django 6.0.7 on 2026-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadata',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='AI generated executive summary of contract.', null=True),
        ),
    ]
