from unittest.mock import patch, MagicMock
from django.test import TestCase
from apps.analysis.services.gemini_service import GeminiService
from apps.analysis.services.text_preprocessor import TextPreprocessingService


class GeminiServiceTests(TestCase):
    """
    Tests for Google Gemini API integration and text preprocessing.
    All external API calls are strictly mocked so unit tests never require a live API key.
    """

    def test_text_preprocessing(self):
        raw_input = "  SECTION 1. DEFINITIONS \r\n\r\n\r\n  This is line 1. \n\n This is line 2.  "
        cleaned = TextPreprocessingService.clean_text(raw_input)
        self.assertNotIn("\r", cleaned)
        self.assertNotIn("\n\n\n", cleaned)
        self.assertTrue(cleaned.startswith("SECTION 1."))

    def test_gemini_missing_api_key_fallback(self):
        with patch.object(GeminiService, 'get_api_key', return_value=""):
            summary = GeminiService.summarize_contract("Sample contract text")
            self.assertIn("GEMINI_API_KEY is not configured", summary)

    @patch('requests.post')
    def test_gemini_summarize_contract_success(self, mock_post):
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "candidates": [
                {
                    "content": {
                        "parts": [
                            {"text": "This is an AI summary generated by Gemini."}
                        ]
                    }
                }
            ]
        }
        mock_post.return_value = mock_response

        with patch.object(GeminiService, 'get_api_key', return_value="test_mock_key"):
            summary = GeminiService.summarize_contract("Valid contract text for test.")
            self.assertEqual(summary, "This is an AI summary generated by Gemini.")

    @patch('requests.post')
    def test_gemini_explain_clause_success(self, mock_post):
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "candidates": [
                {
                    "content": {
                        "parts": [
                            {"text": "This clause means that neither party can disclose secrets."}
                        ]
                    }
                }
            ]
        }
        mock_post.return_value = mock_response

        with patch.object(GeminiService, 'get_api_key', return_value="test_mock_key"):
            explanation = GeminiService.explain_clause("Recipient agrees to non-disclosure.", "CONFIDENTIALITY")
            self.assertEqual(explanation, "This clause means that neither party can disclose secrets.")
