# Generated by Django 5.0.14 on 2026-07-21 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the risk flag', primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='The severity level of the risk', max_length=20)),
                ('risk_keyword', models.CharField(blank=True, help_text='A keyword or short description of the flagged risk', max_length=100, null=True)),
                ('explanation', models.TextField(help_text='A detailed description explaining why this was flagged as a risk')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the risk flag was created')),
                ('document', models.ForeignKey(help_text='The document where the risk was detected', on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='contracts.document')),
                ('extracted_clause', models.ForeignKey(blank=True, help_text='The extracted clause containing the risk (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='parser.extractedclause')),
            ],
            options={
                'verbose_name': 'Risk Flag',
                'verbose_name_plural': 'Risk Flags',
                'db_table': 'risk_engine_risk_flag',
                'ordering': ['-created_at'],
            },
        ),
    ]
